#define EQUALS                           1
#define ADD                              2
#define SUB                              3
#define MULT                             4
#define DIV                              5
#define MOD                              6
#define SEMICOLON                        7
#define IDENTIFIER                       8
#define INTEGER                          9
#define DOUBLE                          10
